name: Auto commit

on:

  push:
    branches:
      - main
      
  schedule:
  - cron: "1 * * * *" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@main      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "rockchethan1111@gmail.com"
          git config --local user.name "chethanyadav456"
          git add -A
          
          arr[0]="raaz(bot): 😂 auto commit"
          arr[1]="raaz(bot): 😱 auto commit"
          arr[2]="raaz(bot): 👿 auto commit"
          arr[3]="raaz(bot): 💩 auto commit"
          arr[4]="raaz(bot): 🙏 auto commit"
          arr[5]="raaz(bot): 🙈 auto commit"
          arr[6]="raaz(bot): 🐐 auto commit"
          arr[7]="raaz(bot): 🤖 auto commit"
          arr[8]="raaz(bot): 🟩 auto commit"
          arr[9]="raaz(bot): 👻 auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}